#!/usr/bin/lua

io.popen("/usr/sbin/lctl white")
io.popen("/usr/sbin/lctl bright")

print("Content-Type: text/html")
print("")
print("<!DOCTYPE html>")
print("<html><body><h1>On</h1></body></html>")
print("")

